import fs from 'node:fs';
import path from 'node:path';

const project = process.argv[2];
if (!project) throw new Error('Usage: node integrate_stem_library.mjs /path/to/project');

const familyFile = path.join(project, 'fiche-famille/data/familles.json');
const patternFile = path.join(project, 'plant-patterns/index.html');
const data = JSON.parse(fs.readFileSync(familyFile, 'utf8'));

const images = [
  { family:'Convolvulaceae', scientific:'Ipomoea pes-caprae', file:'convolvulaceae__ipomoea-pes-caprae__dsc-0043.jpg', validation:'nom fourni', patterns:['tige rampante','tige prostrée','tige herbacée','nœuds visibles'] },
  { family:'Anacardiaceae', scientific:'Toxicodendron radicans', file:'anacardiaceae__toxicodendron-radicans__img-9780.jpg', validation:'nom fourni', patterns:['tige grimpante','tige ligneuse','racines adventives d’accrochage'] },
  { family:'Lauraceae', scientific:'Cassytha filiformis', file:'lauraceae__cassytha-filiformis__img-8893.jpg', validation:'nom fourni', patterns:['tige volubile','tige filiforme','plante parasite'] },
  { family:'Burseraceae', scientific:'Bursera simaruba', file:'burseraceae__bursera-simaruba__img-5239.jpg', validation:'nom fourni', patterns:['tige ligneuse','port arborescent','écorce exfoliante','lenticelles visibles'] },
  { family:'Araceae', scientific:'Epipremnum pinnatum', file:'araceae__epipremnum-pinnatum__img-2245.jpg', validation:'nom fourni', patterns:['tige grimpante','racines adventives d’accrochage','nœuds visibles'] },
  { family:'Arecaceae', scientific:'Arecaceae sp.', file:'arecaceae__sp__img-3103.jpg', validation:'identification à vérifier', patterns:['stipe','tige dressée','port arborescent','cicatrices foliaires annelées','identification à vérifier'] },
  { family:'Arecaceae', scientific:'Arecaceae sp.', file:'arecaceae__sp__img-3162.jpg', validation:'identification à vérifier', patterns:['stipe','tige dressée','port arborescent','identification à vérifier'] },
];

if (!data.organes.includes('Tige')) data.organes.push('Tige');
for (const family of data.familles) {
  if (family.organes.Tige) family.organes.Tige = family.organes.Tige.filter(p => !String(p.img || '').startsWith('stem-library-v1/'));
}
for (const item of images) {
  let family = data.familles.find(f => f.fam === item.family);
  if (!family) {
    family = { fam:item.family, note:'Famille ajoutée au catalogue des tiges; signature familiale à compléter après validation botanique.', organes:{} };
    data.familles.push(family);
  }
  family.organes.Tige ??= [];
  const img = `stem-library-v1/${item.file}`;
  const entry = { img, nom:item.scientific, patterns:item.patterns, validation:item.validation, source:'Photo_tiges_nommees' };
  const list = family.organes.Tige;
  const oldIndex = list.findIndex(p => p.img === img);
  if (oldIndex >= 0) list[oldIndex] = entry; else list.push(entry);
}
fs.writeFileSync(familyFile, JSON.stringify(data,null,1)+'\n');

let html = fs.readFileSync(patternFile,'utf8');
const marker = 'function drawMenu(query=\'\')';
if (!html.includes(marker)) throw new Error('Plant Patterns marker not found');
const block = `
/* STEM_LIBRARY_V1_START — generated by scripts/integrate_stem_library.mjs */
Object.assign(L,{
 stipe:ST('Port et croissance','Stipe','Tige arborescente typique de nombreux palmiers, généralement non ramifiée et sans croissance secondaire comparable à celle d’un tronc ligneux de dicotylédone. Une palme est une feuille; le stipe est la tige qui porte la couronne de palmes.','Rechercher un axe dressé, les cicatrices des anciennes feuilles et l’absence habituelle de vraies branches sur le même stipe.')
});
const stemLibraryBase='../fiche-famille/stem-library-v1/';
const stemLibrary={
 ipomoea:stemLibraryBase+'convolvulaceae__ipomoea-pes-caprae__dsc-0043.jpg',
 toxicodendron:stemLibraryBase+'anacardiaceae__toxicodendron-radicans__img-9780.jpg',
 cassytha:stemLibraryBase+'lauraceae__cassytha-filiformis__img-8893.jpg',
 bursera:stemLibraryBase+'burseraceae__bursera-simaruba__img-5239.jpg',
 epipremnum:stemLibraryBase+'araceae__epipremnum-pinnatum__img-2245.jpg',
 palmRinged:stemLibraryBase+'arecaceae__sp__img-3103.jpg',
 palmHabit:stemLibraryBase+'arecaceae__sp__img-3162.jpg'
};
const stemPhotoSets={
 stem:Object.values(stemLibrary),
 stemNode:[stemLibrary.epipremnum],
 stemLenticel:[stemLibrary.bursera],stemBark:[stemLibrary.bursera],
 herbaceousStem:[stemLibrary.ipomoea],
 woodyStem:[stemLibrary.toxicodendron,stemLibrary.bursera],
 erectStem:[stemLibrary.bursera,stemLibrary.palmRinged,stemLibrary.palmHabit],
 prostrateStem:[stemLibrary.ipomoea],creepingStem:[stemLibrary.ipomoea],
 climbingStem:[stemLibrary.toxicodendron,stemLibrary.epipremnum],
 twiningStem:[stemLibrary.cassytha],arborescentStem:[stemLibrary.bursera,stemLibrary.palmRinged,stemLibrary.palmHabit],
 adventitiousRootStem:[stemLibrary.toxicodendron,stemLibrary.epipremnum],
 stipe:[stemLibrary.palmRinged,stemLibrary.palmHabit]
};
Object.entries(stemPhotoSets).forEach(([id,photos])=>{if(L[id])L[id].p=photos});
Object.assign(mediaTraits,{
 [stemLibrary.ipomoea]:['Convolvulaceae','Ipomoea pes-caprae','Tige rampante','Tige prostrée','Tige herbacée','Nom fourni — photo examinée'],
 [stemLibrary.toxicodendron]:['Anacardiaceae','Toxicodendron radicans','Tige grimpante','Tige ligneuse','Racines adventives d’accrochage','Nom fourni — photo examinée'],
 [stemLibrary.cassytha]:['Lauraceae','Cassytha filiformis','Tige volubile','Tige filiforme','Plante parasite','Nom fourni — photo examinée'],
 [stemLibrary.bursera]:['Burseraceae','Bursera simaruba','Tige ligneuse','Écorce exfoliante','Lenticelles','Nom fourni — photo examinée'],
 [stemLibrary.epipremnum]:['Araceae','Epipremnum pinnatum','Tige grimpante','Nœuds','Racines adventives d’accrochage','Nom fourni — photo examinée'],
 [stemLibrary.palmRinged]:['Arecaceae','Arecaceae sp.','Stipe','Tige dressée','Cicatrices foliaires annelées','Identification spécifique à vérifier'],
 [stemLibrary.palmHabit]:['Arecaceae','Arecaceae sp.','Stipe','Port arborescent','Tige dressée','Identification spécifique à vérifier']
});
/* STEM_LIBRARY_V1_END */
`;
const start = '/* STEM_LIBRARY_V1_START';
const end = '/* STEM_LIBRARY_V1_END */';
if (html.includes(start)) {
  const before = html.slice(0,html.indexOf(start)).trimEnd();
  const after = html.slice(html.indexOf(end)+end.length).trimStart();
  html = `${before}\n\n${block.trim()}\n\n${after}`;
} else html = html.replace(marker, '\n'+block.trim()+'\n\n'+marker);
html = html.replaceAll('<button data-route="stipe">Type : stipe</button><button data-route="stipe">Type : stipe</button>', '<button data-route="stipe">Type : stipe</button>');
if (!html.includes('<button data-route="stipe">Type : stipe</button>')) {
  html = html.replace('<button data-route="stemNode">Anatomie : nœud</button><button data-route="climbingStem">Port : grimpante</button>', '<button data-route="stemNode">Anatomie : nœud</button><button data-route="climbingStem">Port : grimpante</button><button data-route="stipe">Type : stipe</button>');
}
fs.writeFileSync(patternFile,html);

console.log(JSON.stringify({families:data.familles.length,organs:data.organes,stemPhotos:images.length},null,2));
